# Secrets for TIFA - Local Development
# For production deployment, add your real API keys

GEMINI_API_KEY_1 = "your-gemini-api-key-1-here"
GEMINI_API_KEY_2 = "your-gemini-api-key-2-here"

# Optional additional keys for load balancing
GEMINI_API_KEY_3 = ""
GEMINI_API_KEY_4 = ""
